apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hrms-app
  template:
    metadata:
      labels:
        app: hrms-app
    spec:
      containers:
      - name: hrms-app
        image: hrms-app:latest
        imagePullPolicy: Never       # <--- Add this line
        ports:
        - containerPort: 3001
